"""Helpers for discovering and parsing moth image files.

Images live outside this repo and follow the naming convention::

    {tax_id}_observation_{obs_id}_photo_{photo_id}.{ext}

Files are organized into one subfolder per ``tax_id`` under each base directory
(images, labels, classes and the thumbnail/metric cache), e.g.::

    <images>/<tax_id>/<tax_id>_observation_..._photo_....jpg
    <labels>/<tax_id>/<tax_id>_observation_..._photo_....txt

The filenames themselves are never changed and still begin with the ``tax_id``,
so the correct subfolder for any file is derived from its own name."""

from .paths import (
    FILENAME_RE,
    MothImage,
    _tax_subdir,
    _unlink_quiet,
    find_image,
    get_image_dir,
    get_image_path,
    get_image_size,
    get_thumbnail_dir,
    group_by_tax_id,
    image_basename,
    list_tax_ids,
    parse_filename,
    scan_images,
    scan_tax_images,
    tax_id_for_file,
)
from .names import (
    _EMPTY_NAME_INFO,
    _NAMES_CACHE,
    _OBSERVATIONS_CACHE,
    get_name_info,
    get_names_csv_path,
    get_observation_info,
    get_observations_path,
    load_names,
    load_observations,
)
from .classes import (
    FLAGS,
    FLAG_TABLE,
    Flag,
    NO_NORM_FLAGS,
    NO_TRAIN_FLAGS,
    STAGES,
    _DETAILS_PREFIX,
    _FLAGS_PREFIX,
    _FLAG_BY_NAME,
    _POSE_PREFIX,
    _read_class_details,
    _read_class_file,
    _read_class_pose,
    _write_class_file,
    clear_image_class,
    flag_applies_to_stage,
    flag_stages,
    flags_block_training,
    flags_for_stage,
    flags_suppress_normalization,
    get_class_and_flags,
    get_class_dir,
    get_class_path,
    get_image_class,
    get_image_details,
    get_image_flags,
    get_starred_path,
    is_image_starred,
    load_starred,
    set_image_class,
    set_image_details,
    set_image_flags,
    set_image_starred,
)
from .annotations import (
    Annotation,
    KEYPOINT_LABELS,
    Keypoint,
    POSE_BOTTOM_UP,
    POSE_NONE,
    POSE_SIDE,
    POSE_TOP_DOWN,
    POSE_UNCLEAR,
    _pose_source_keypoints,
    _read_annotations,
    _valid_frlb,
    classify_annotation,
    classify_pose,
    get_class_and_flags_with_source,
    get_label_dir,
    get_label_path,
    get_pose_dir,
    get_pose_path,
    get_predicted_class_and_flags,
    get_predicted_pose_class,
    get_prediction_class_path,
    get_prediction_dir,
    get_prediction_path,
    load_annotations,
    load_pose_source,
    load_poses,
    load_predictions,
    parse_label_line,
    read_annotations_file,
)
from .metrics import (
    SHARPNESS_CENTER_FRAC,
    SHARPNESS_SCORE_A,
    SHARPNESS_SCORE_B,
    SHARPNESS_SIZE,
    annotation_symmetry,
    compute_sharpness,
    cumulative_score,
    pose_pixel_span,
    pose_symmetry_metric,
    score_components,
    sharpness_score,
)
from .normalize import (
    NORM_FILL,
    NORM_GEOM_VERSION,
    NORM_SIDE_CIRCLE_RADIUS,
    NORM_SIDE_FB_Y,
    NORM_TOPDOWN_CIRCLE_RADIUS,
    NORM_TOPDOWN_CROP_SCALE,
    _iter_normalized_files,
    _normalized_paths,
    _side_normalization,
    clear_normalized,
    compute_normalization,
    get_or_create_normalized,
    get_or_create_thumbnail,
    touch_normalized,
)
from .wingstats import (
    WING_STATS_ALPHA,
    WING_STATS_AXIS,
    WING_STATS_BG,
    WING_STATS_DOT_RADIUS,
    WING_STATS_L_COLOR,
    WING_STATS_MARGIN,
    WING_STATS_MARK,
    WING_STATS_MIN,
    WING_STATS_R_COLOR,
    WING_STATS_SIZE,
    WING_STATS_WING_COLOR,
    _render_wing_scatter,
    _side_wing_points,
    _top_down_wing_points,
    build_side_wing_stats,
    build_wing_stats,
    get_side_wing_stats_path,
    get_wing_stats_path,
)
from .posedata import (
    POSE_DATA_VERSION,
    _write_pose_data,
    build_pose_data,
    choose_tax_thumbnail,
    compute_pose_row,
    get_pose_data,
    get_pose_data_path,
    get_tax_thumbnail,
    load_pose_data,
    load_pose_data_raw,
    mark_pose_row_stale,
    pose_data_version_ok,
    refresh_tax_thumbnail,
    set_pose_row_flags,
    verify_pose_row,
)
from .summary import (
    SOURCE_STAGES,
    SUMMARY_VERSION,
    TAX_TREE_VERSION,
    VIEW_POSES,
    _NO_SUBFAMILY,
    _UNKNOWN_TAXON,
    _aggregate_children,
    _build_species_leaf,
    _compute_summary_counts,
    _empty_genus_node,
    _empty_parent_node,
    _fmt,
    _genus_counts,
    _genus_node_from,
    _parent_node_from,
    _parse_obs,
    _pick_thumbnail,
    _refresh_genus_node,
    _refresh_parent_node,
    _source_stage_bucket,
    _species_summary_state,
    _tax_lineage_keys,
    _write_summary,
    _write_tax_summary,
    build_summary,
    build_tax_summary,
    compute_source_data,
    delete_image_files,
    delete_images,
    get_summary,
    get_summary_path,
    get_tax_summary_path,
    load_summary,
    load_tax_summary,
    prune_observations,
    prune_pose_data,
    save_annotations,
    soft_update_tax_summary,
    update_summary,
)
